[package]
name = "oxvg_style"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxvg_selectors = { workspace = true }

lightningcss = { workspace = true }
markup5ever = { workspace = true }
rcdom = { workspace = true }
