/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Optimise an SVG document using the provided config
 *
 * # Errors
 * - If the document fails to parse
 * - If any of the optimisations fail
 * - If the optimised document fails to serialize
 */
export declare function optimise(svg: string, configJson?: string | undefined | null): string
