use std::collections::{HashMap, HashSet};

use crate::collections::{AttrsGroups, ElementGroup};

pub struct AllowedContent {
    pub attrs_groups: HashSet<AttrsGroups>,
    pub attrs: Option<HashSet<&'static str>>,
    pub defaults: Option<HashMap<&'static str, &'static str>>,
    pub deprecated_safe: Option<HashSet<&'static str>>,
    pub deprecated_unsafe: Option<HashSet<&'static str>>,
    pub content_groups: Option<HashSet<ElementGroup>>,
    pub content: Option<HashSet<&'static str>>,
}

lazy_static! {
    pub static ref ELEMS: HashMap<&'static str, AllowedContent> = HashMap::from([
        (
            "a",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "style",
                    "target",
                    "transform",
                ])),
                defaults: Some(HashMap::from([("target", "_self")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                    "tspan",
                ])),
            },
        ),
        (
            "altGlyph",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "dx",
                    "dy",
                    "externalResourcesRequired",
                    "format",
                    "glyphRef",
                    "rotate",
                    "style",
                    "x",
                    "y",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "altGlyphDef",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["glyphRef"])),
            },
        ),
        (
            "altGlyphItem",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["glyphRef", "altGlyphItem"])),
            },
        ),
        (
            "animate",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::AnimationAddition,
                    AttrsGroups::AnimationAttributeTarget,
                    AttrsGroups::AnimationEvent,
                    AttrsGroups::AnimationTiming,
                    AttrsGroups::AnimationValue,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from(["externalResourcesRequired"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "animateColor",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::AnimationAddition,
                    AttrsGroups::AnimationAttributeTarget,
                    AttrsGroups::AnimationEvent,
                    AttrsGroups::AnimationTiming,
                    AttrsGroups::AnimationValue,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from(["externalResourcesRequired"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "animateMotion",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::AnimationAddition,
                    AttrsGroups::AnimationEvent,
                    AttrsGroups::AnimationTiming,
                    AttrsGroups::AnimationValue,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "externalResourcesRequired",
                    "keyPoints",
                    "origin",
                    "path",
                    "rotate",
                ])),
                defaults: Some(HashMap::from([("rotate", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from(["mpath"])),
            },
        ),
        (
            "animateTransform",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::AnimationAddition,
                    AttrsGroups::AnimationAttributeTarget,
                    AttrsGroups::AnimationEvent,
                    AttrsGroups::AnimationTiming,
                    AttrsGroups::AnimationValue,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from(["externalResourcesRequired", "type"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "circle",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "cx",
                    "cy",
                    "externalResourcesRequired",
                    "r",
                    "style",
                    "transform",
                ])),
                defaults: Some(HashMap::from([("cx", "0"), ("cy", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "clipPath",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::Presentation
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "clipPathUnits",
                    "externalResourcesRequired",
                    "style",
                    "transform",
                ])),
                defaults: Some(HashMap::from([("clipPathUnits", "userSpaceOnUse")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::Shape
                ])),
                content: Some(HashSet::from(["text", "use"])),
            },
        ),
        (
            "color-profile",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::XLink]),
                attrs: Some(HashSet::from(["local", "name", "rendering-intent"])),
                defaults: Some(HashMap::from([
                    ("name", "sRGB"),
                    ("rendering-intent", "auto"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["name"])),
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "cursor",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from(["externalResourcesRequired", "x", "y"])),
                defaults: Some(HashMap::from([("x", "0"), ("y", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "defs",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "desc",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "ellipse",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "cx",
                    "cy",
                    "externalResourcesRequired",
                    "rx",
                    "ry",
                    "style",
                    "transform",
                ])),
                defaults: Some(HashMap::from([("cx", "0"), ("cy", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "feBlend",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in", "in2", "mode"])),
                defaults: Some(HashMap::from([("mode", "normal")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feColorMatrix",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in", "type", "values"])),
                defaults: Some(HashMap::from([("type", "matrix")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feComponentTransfer",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["feFuncA", "feFuncB", "feFuncG", "feFuncR"])),
            },
        ),
        (
            "feComposite",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class", "in", "in2", "k1", "k2", "k3", "k4", "operator", "style",
                ])),
                defaults: Some(HashMap::from([
                    ("operator", "over"),
                    ("k1", "0"),
                    ("k2", "0"),
                    ("k3", "0"),
                    ("k4", "0"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feConvolveMatrix",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "in",
                    "kernelMatrix",
                    "order",
                    "style",
                    "bias",
                    "divisor",
                    "edgeMode",
                    "targetX",
                    "targetY",
                    "kernelUnitLength",
                    "preserveAlpha",
                ])),
                defaults: Some(HashMap::from([
                    ("order", "3"),
                    ("bias", "0"),
                    ("edgeMode", "duplicate"),
                    ("preserveAlpha", "false"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feDiffuseLighting",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "diffuseConstant",
                    "in",
                    "kernelUnitLength",
                    "style",
                    "surfaceScale",
                ])),
                defaults: Some(HashMap::from([
                    ("surfaceScale", "1"),
                    ("diffuseConstant", "1"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "feDistantLight",
                    "fePointLight",
                    "feSpotLight",
                ])),
            },
        ),
        (
            "feDisplacementMap",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "in",
                    "in2",
                    "scale",
                    "style",
                    "xChannelSelector",
                    "yChannelSelector",
                ])),
                defaults: Some(HashMap::from([
                    ("scale", "0"),
                    ("xChannelSelector", "A"),
                    ("yChannelSelector", "A"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feDistantLight",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["azimuth", "elevation"])),
                defaults: Some(HashMap::from([("azimuth", "0"), ("elevation", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feFlood",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "animateColor", "set"])),
            },
        ),
        (
            "feFuncA",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::TransferFunction]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["set", "animate"])),
            },
        ),
        (
            "feFuncB",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::TransferFunction]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["set", "animate"])),
            },
        ),
        (
            "feFuncG",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::TransferFunction]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["set", "animate"])),
            },
        ),
        (
            "feFuncR",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::TransferFunction]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["set", "animate"])),
            },
        ),
        (
            "feGaussianBlur",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in", "stdDeviation"])),
                defaults: Some(HashMap::from([("stdDeviation", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["set", "animate"])),
            },
        ),
        (
            "feImage",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "href",
                    "preserveAspectRatio",
                    "style",
                    "xlink:href",
                ])),
                defaults: Some(HashMap::from([("preserveAspectRatio", "xMidYMid meet")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "animateTransform", "set"])),
            },
        ),
        (
            "feMerge",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["feMergeNode"])),
            },
        ),
        (
            "feMergeNode",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["in"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feMorphology",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class", "style", "in", "operator", "radius",
                ])),
                defaults: Some(HashMap::from([("operator", "erode"), ("radius", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feOffset",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in", "dx", "dy"])),
                defaults: Some(HashMap::from([("dx", "0"), ("dy", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "fePointLight",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["x", "y", "z"])),
                defaults: Some(HashMap::from([("x", "0"), ("y", "0"), ("z", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feSpecularLighting",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "in",
                    "kernelUnitLength",
                    "specularConstant",
                    "specularExponent",
                    "style",
                    "surfaceScale",
                ])),
                defaults: Some(HashMap::from([
                    ("surfaceScale", "1"),
                    ("specularConstant", "1"),
                    ("specularExponent", "1"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Descriptive,
                    ElementGroup::LightSource
                ])),
                content: None,
            },
        ),
        (
            "feSpotLight",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from([
                    "limitingConeAngle",
                    "pointsAtX",
                    "pointsAtY",
                    "pointsAtZ",
                    "specularExponent",
                    "x",
                    "y",
                    "z",
                ])),
                defaults: Some(HashMap::from([
                    ("x", "0"),
                    ("y", "0"),
                    ("z", "0"),
                    ("pointsAtX", "0"),
                    ("pointsAtY", "0"),
                    ("pointsAtZ", "0"),
                    ("specularExponent", "1"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feTile",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from(["class", "style", "in"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "feTurbulence",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::FilterPrimitive
                ]),
                attrs: Some(HashSet::from([
                    "baseFrequency",
                    "class",
                    "numOctaves",
                    "seed",
                    "stitchTiles",
                    "style",
                    "type",
                ])),
                defaults: Some(HashMap::from([
                    ("baseFrequency", "0"),
                    ("numOctaves", "1"),
                    ("seed", "0"),
                    ("stitchTiles", "noStitch"),
                    ("type", "turbulence"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "filter",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "filterRes",
                    "filterUnits",
                    "height",
                    "href",
                    "primitiveUnits",
                    "style",
                    "width",
                    "x",
                    "xlink:href",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("primitiveUnits", "userSpaceOnUse"),
                    ("x", "-10%"),
                    ("y", "-10%"),
                    ("width", "120%"),
                    ("height", "120%"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["filterRes"])),
                content_groups: Some(HashSet::from([
                    ElementGroup::Descriptive,
                    ElementGroup::FilterPrimitive
                ])),
                content: Some(HashSet::from(["animate", "set"])),
            },
        ),
        (
            "font",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "horiz-adv-x",
                    "horiz-origin-x",
                    "horiz-origin-y",
                    "style",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                defaults: Some(HashMap::from([
                    ("horiz-origin-x", "0"),
                    ("horiz-origin-y", "0"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from([
                    "horiz-origin-x",
                    "horiz-origin-y",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "font-face",
                    "glyph",
                    "hkern",
                    "missing-glyph",
                    "vkern",
                ])),
            },
        ),
        (
            "font-face",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from([
                    "font-family",
                    "font-style",
                    "font-variant",
                    "font-weight",
                    "font-stretch",
                    "font-size",
                    "unicode-range",
                    "units-per-em",
                    "panose-1",
                    "stemv",
                    "stemh",
                    "slope",
                    "cap-height",
                    "x-height",
                    "accent-height",
                    "ascent",
                    "descent",
                    "widths",
                    "bbox",
                    "ideographic",
                    "alphabetic",
                    "mathematical",
                    "hanging",
                    "v-ideographic",
                    "v-alphabetic",
                    "v-mathematical",
                    "v-hanging",
                    "underline-position",
                    "underline-thickness",
                    "strikethrough-position",
                    "strikethrough-thickness",
                    "overline-position",
                    "overline-thickness",
                ])),
                defaults: Some(HashMap::from([
                    ("font-style", "all"),
                    ("font-variant", "normal"),
                    ("font-weight", "all"),
                    ("font-stretch", "normal"),
                    ("unicode-range", "U+0-10FFFF"),
                    ("units-per-em", "1000"),
                    ("panose-1", "0 0 0 0 0 0 0 0 0 0"),
                    ("slope", "0"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from([
                    "accent-height",
                    "alphabetic",
                    "ascent",
                    "bbox",
                    "cap-height",
                    "descent",
                    "hanging",
                    "ideographic",
                    "mathematical",
                    "panose-1",
                    "slope",
                    "stemh",
                    "stemv",
                    "unicode-range",
                    "units-per-em",
                    "v-alphabetic",
                    "v-hanging",
                    "v-ideographic",
                    "v-mathematical",
                    "widths",
                    "x-height",
                ])),
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from(["font-face-src"])),
            },
        ),
        (
            "font-face-format",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["string"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["string"])),
                content_groups: None,
                content: None,
            },
        ),
        (
            "font-face-name",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["name"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["name"])),
                content_groups: None,
                content: None,
            },
        ),
        (
            "font-face-src",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["font-face-name", "font-face-uri"])),
            },
        ),
        (
            "font-face-uri",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::XLink]),
                attrs: Some(HashSet::from(["href", "xlink:href"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["font-face-format"])),
            },
        ),
        (
            "foreignObject",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "style",
                    "transform",
                    "width",
                    "x",
                    "y",
                ])),
                defaults: Some(HashMap::from([("x", "0"), ("y", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "g",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "glyph",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from([
                    "arabic-form",
                    "class",
                    "d",
                    "glyph-name",
                    "horiz-adv-x",
                    "lang",
                    "orientation",
                    "style",
                    "unicode",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                defaults: Some(HashMap::from([("arabic-form", "initial")])),
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from([
                    "arabic-form",
                    "glyph-name",
                    "horiz-adv-x",
                    "orientation",
                    "unicode",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "glyphRef",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from([
                    "class",
                    "d",
                    "horiz-adv-x",
                    "style",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from([
                    "horiz-adv-x",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "hatch",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "hatchContentUnits",
                    "hatchUnits",
                    "pitch",
                    "rotate",
                    "style",
                    "transform",
                    "x",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("hatchUnits", "objectBoundingBox"),
                    ("hatchContentUnits", "userSpaceOnUse"),
                    ("x", "0"),
                    ("y", "0"),
                    ("pitch", "0"),
                    ("rotate", "0"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: Some(HashSet::from(["hatchPath"])),
            },
        ),
        (
            "hatchPath",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from(["class", "style", "d", "offset"])),
                defaults: Some(HashMap::from([("offset", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "hkern",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["u1", "g1", "u2", "g2", "k"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["g1", "g2", "k", "u1", "u2"])),
                content_groups: None,
                content: None,
            },
        ),
        (
            "image",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "href",
                    "preserveAspectRatio",
                    "style",
                    "transform",
                    "width",
                    "x",
                    "xlink:href",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("x", "0"),
                    ("y", "0"),
                    ("preserveAspectRatio", "xMidYMid meet"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "line",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "style",
                    "transform",
                    "x1",
                    "x2",
                    "y1",
                    "y2",
                ])),
                defaults: Some(HashMap::from([
                    ("x1", "0"),
                    ("y1", "0"),
                    ("x2", "0"),
                    ("y2", "0"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "linearGradient",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "gradientTransform",
                    "gradientUnits",
                    "href",
                    "spreadMethod",
                    "style",
                    "x1",
                    "x2",
                    "xlink:href",
                    "y1",
                    "y2",
                ])),
                defaults: Some(HashMap::from([
                    ("x1", "0"),
                    ("y1", "0"),
                    ("x2", "100%"),
                    ("y2", "0"),
                    ("spreadMethod", "pad"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "animate",
                    "animateTransform",
                    "set",
                    "stop",
                ])),
            },
        ),
        (
            "marker",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "markerHeight",
                    "markerUnits",
                    "markerWidth",
                    "orient",
                    "preserveAspectRatio",
                    "refX",
                    "refY",
                    "style",
                    "viewBox",
                ])),
                defaults: Some(HashMap::from([
                    ("markerUnits", "strokeWidth"),
                    ("refX", "0"),
                    ("refY", "0"),
                    ("markerWidth", "3"),
                    ("markerHeight", "3"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "mask",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::Presentation
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "mask-type",
                    "maskContentUnits",
                    "maskUnits",
                    "style",
                    "width",
                    "x",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("maskUnits", "objectBoundingBox"),
                    ("maskContentUnits", "userSpaceOnUse"),
                    ("x", "-10%"),
                    ("y", "-10%"),
                    ("width", "120%"),
                    ("height", "120%"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "metadata",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: None,
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "missing-glyph",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from([
                    "class",
                    "d",
                    "horiz-adv-x",
                    "style",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from([
                    "horiz-adv-x",
                    "vert-adv-y",
                    "vert-origin-x",
                    "vert-origin-y",
                ])),
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "mpath",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::XLink]),
                attrs: Some(HashSet::from([
                    "externalResourcesRequired",
                    "href",
                    "xlink:href",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "path",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "d",
                    "externalResourcesRequired",
                    "pathLength",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "pattern",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "href",
                    "patternContentUnits",
                    "patternTransform",
                    "patternUnits",
                    "preserveAspectRatio",
                    "style",
                    "viewBox",
                    "width",
                    "x",
                    "xlink:href",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("patternUnits", "objectBoundingBox"),
                    ("patternContentUnits", "userSpaceOnUse"),
                    ("x", "0"),
                    ("y", "0"),
                    ("width", "0"),
                    ("height", "0"),
                    ("preserveAspectRatio", "xMidYMid meet"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "polygon",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "points",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "polyline",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "points",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "radialGradient",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "cx",
                    "cy",
                    "externalResourcesRequired",
                    "fr",
                    "fx",
                    "fy",
                    "gradientTransform",
                    "gradientUnits",
                    "href",
                    "r",
                    "spreadMethod",
                    "style",
                    "xlink:href",
                ])),
                defaults: Some(HashMap::from([
                    ("gradientUnits", "objectBoundingBox"),
                    ("cx", "50%"),
                    ("cy", "50%"),
                    ("r", "50%"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "animate",
                    "animateTransform",
                    "set",
                    "stop",
                ])),
            },
        ),
        (
            "meshGradient",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "style",
                    "x",
                    "y",
                    "gradientUnits",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Animation
                ])),
                content: Some(HashSet::from(["meshRow"])),
            },
        ),
        (
            "meshRow",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from(["meshPatch"])),
            },
        ),
        (
            "meshPatch",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from(["stop"])),
            },
        ),
        (
            "rect",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "rx",
                    "ry",
                    "style",
                    "transform",
                    "width",
                    "x",
                    "y",
                ])),
                defaults: Some(HashMap::from([("x", "0"), ("y", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "script",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::XLink]),
                attrs: Some(HashSet::from([
                    "externalResourcesRequired",
                    "type",
                    "href",
                    "xlink:href",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "set",
            AllowedContent {
                attrs_groups: HashSet::from([
                    // NOTE: This is in SVGO for some reason? Should resolve to undefined I guess
                    // AttrsGroups::Animation,
                    AttrsGroups::AnimationAttributeTarget,
                    AttrsGroups::AnimationTiming,
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from(["externalResourcesRequired", "to"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "solidColor",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::PaintServer])),
                content: None,
            },
        ),
        (
            "stop",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core, AttrsGroups::Presentation]),
                attrs: Some(HashSet::from(["class", "style", "offset", "path"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: Some(HashSet::from(["animate", "animateColor", "set"])),
            },
        ),
        (
            "style",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["type", "media", "title"])),
                defaults: Some(HashMap::from([("type", "text/css")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "svg",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::DocumentEvent,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "baseProfile",
                    "class",
                    "contentScriptType",
                    "contentStyleType",
                    "height",
                    "preserveAspectRatio",
                    "style",
                    "version",
                    "viewBox",
                    "width",
                    "x",
                    "y",
                    "zoomAndPan",
                ])),
                defaults: Some(HashMap::from([
                    ("x", "0"),
                    ("y", "0"),
                    ("width", "100%"),
                    ("height", "100%"),
                    ("preserveAspectRatio", "xMidYMid meet"),
                    ("zoomAndPan", "magnify"),
                    ("version", "1.1"),
                    ("baseProfile", "none"),
                    ("contentScriptType", "application/ecmascript"),
                    ("contentStyleType", "text/css"),
                ])),
                deprecated_safe: Some(HashSet::from(["version"])),
                deprecated_unsafe: Some(HashSet::from([
                    "baseProfile",
                    "contentScriptType",
                    "contentStyleType",
                    "zoomAndPan",
                ])),
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "switch",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "style",
                    "transform",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::Shape
                ])),
                content: Some(HashSet::from([
                    "a",
                    "foreignObject",
                    "g",
                    "image",
                    "svg",
                    "switch",
                    "text",
                    "use",
                ])),
            },
        ),
        (
            "symbol",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "preserveAspectRatio",
                    "refX",
                    "refY",
                    "style",
                    "viewBox",
                ])),
                defaults: Some(HashMap::from([("refX", "0"), ("refY", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::PaintServer,
                    ElementGroup::Shape,
                    ElementGroup::Structural,
                ])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyphDef",
                    "clipPath",
                    "color-profile",
                    "cursor",
                    "filter",
                    "font-face",
                    "font",
                    "foreignObject",
                    "image",
                    "marker",
                    "mask",
                    "pattern",
                    "script",
                    "style",
                    "switch",
                    "text",
                    "view",
                ])),
            },
        ),
        (
            "text",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "dx",
                    "dy",
                    "externalResourcesRequired",
                    "lengthAdjust",
                    "rotate",
                    "style",
                    "textLength",
                    "transform",
                    "x",
                    "y",
                ])),
                defaults: Some(HashMap::from([
                    ("x", "0"),
                    ("y", "0"),
                    ("lengthAdjust", "spacing"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive,
                    ElementGroup::TextContentChild,
                ])),
                content: Some(HashSet::from(["a"])),
            },
        ),
        (
            "textPath",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "d",
                    "externalResourcesRequired",
                    "href",
                    "method",
                    "spacing",
                    "startOffset",
                    "style",
                    "xlink:href",
                ])),
                defaults: Some(HashMap::from([
                    ("startOffset", "0"),
                    ("method", "align"),
                    ("spacing", "exact"),
                ])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyph",
                    "animate",
                    "animateColor",
                    "set",
                    "tref",
                    "tspan",
                ])),
            },
        ),
        (
            "title",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["class", "style"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: None,
                content: None,
            },
        ),
        (
            "tref",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "href",
                    "style",
                    "xlink:href",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from(["animate", "animateColor", "set"])),
            },
        ),
        (
            "tspan",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "dx",
                    "dy",
                    "externalResourcesRequired",
                    "lengthAdjust",
                    "rotate",
                    "style",
                    "textLength",
                    "x",
                    "y",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: Some(HashSet::from([
                    "a",
                    "altGlyph",
                    "animate",
                    "animateColor",
                    "set",
                    "tref",
                    "tspan",
                ])),
            },
        ),
        (
            "use",
            AllowedContent {
                attrs_groups: HashSet::from([
                    AttrsGroups::ConditionalProcessing,
                    AttrsGroups::Core,
                    AttrsGroups::GraphicalEvent,
                    AttrsGroups::Presentation,
                    AttrsGroups::XLink,
                ]),
                attrs: Some(HashSet::from([
                    "class",
                    "externalResourcesRequired",
                    "height",
                    "href",
                    "style",
                    "transform",
                    "width",
                    "x",
                    "xlink:href",
                    "y",
                ])),
                defaults: Some(HashMap::from([("x", "0"), ("y", "0")])),
                deprecated_safe: None,
                deprecated_unsafe: None,
                content_groups: Some(HashSet::from([
                    ElementGroup::Animation,
                    ElementGroup::Descriptive
                ])),
                content: None,
            },
        ),
        (
            "view",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from([
                    "externalResourcesRequired",
                    "preserveAspectRatio",
                    "viewBox",
                    "viewTarget",
                    "zoomAndPan",
                ])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["viewTarget", "zoomAndPan"])),
                content_groups: Some(HashSet::from([ElementGroup::Descriptive])),
                content: None,
            },
        ),
        (
            "vkern",
            AllowedContent {
                attrs_groups: HashSet::from([AttrsGroups::Core]),
                attrs: Some(HashSet::from(["u1", "g1", "u2", "g2", "k"])),
                defaults: None,
                deprecated_safe: None,
                deprecated_unsafe: Some(HashSet::from(["g1", "g2", "k", "u1", "u2"])),
                content_groups: None,
                content: None,
            },
        ),
    ]);
}
