use oxvg_collections::{
    atom::Atom,
    attribute::AttrId,
    name::{Prefix, QualName},
};

use crate::error::BuildError;

#[allow(clippy::too_many_lines)]
pub fn attr_to_jsx_str<'input>(attr: &AttrId<'input>) -> Result<Atom<'input>, BuildError<'input>> {
    if attr.prefix().value() != attr.unaliased().prefix().value() {
        return Err(BuildError::UnknownXMLPrefixAttr(attr.clone()));
    }
    Ok(match attr {
        // HTML
        AttrId::AutoFocus => "autoFocus",
        AttrId::Class => "className",
        AttrId::CrossOrigin => "crossOrigin",
        AttrId::Hreflang => "hrefLang",
        AttrId::ReferrerPolicy => "referrerPolicy",
        AttrId::Tabindex => "tabIndex",

        // ARIA
        AttrId::AriaActiveDescendant => "aria-activedescendant",
        AttrId::AriaAtomic => "aria-atomic",
        AttrId::AriaAutocomplete => "aria-autocomplete",
        AttrId::AriaBusy => "aria-busy",
        AttrId::AriaChecked => "aria-checked",
        AttrId::AriaColCount => "aria-colcount",
        AttrId::AriaColIndex => "aria-colindex",
        AttrId::AriaColSpan => "aria-colspan",
        AttrId::AriaControls => "aria-controls",
        AttrId::AriaCurrent => "aria-current",
        AttrId::AriaDescribedBy => "aria-describedby",
        AttrId::AriaDetails => "aria-details",
        AttrId::AriaDisabled => "aria-disabled",
        AttrId::AriaDropEffect => "aria-dropeffect",
        AttrId::AriaErrorMessage => "aria-errormessage",
        AttrId::AriaExpanded => "aria-expanded",
        AttrId::AriaFlowTo => "aria-flowto",
        AttrId::AriaGrabbed => "aria-grabbed",
        AttrId::AriaHasPopup => "aria-haspopup",
        AttrId::AriaHidden => "aria-hidden",
        AttrId::AriaInvalid => "aria-invalid",
        AttrId::AriaKeyshortcuts => "aria-keyshortcuts",
        AttrId::AriaLabel => "aria-label",
        AttrId::AriaLabelledBy => "aria-labelledby",
        AttrId::AriaLevel => "aria-level",
        AttrId::AriaLive => "aria-live",
        AttrId::AriaModal => "aria-modal",
        AttrId::AriaMultiline => "aria-multiline",
        AttrId::AriaMultiselectable => "aria-multiselectable",
        AttrId::AriaOrientation => "aria-orientation",
        AttrId::AriaOwns => "aria-owns",
        AttrId::AriaPlaceholder => "aria-placeholder",
        AttrId::AriaPosInSet => "aria-posinset",
        AttrId::AriaPressed => "aria-pressed",
        AttrId::AriaReadonly => "aria-readonly",
        AttrId::AriaRelevant => "aria-relevant",
        AttrId::AriaRequired => "aria-required",
        AttrId::AriaRoleDescription => "aria-roledescription",
        AttrId::AriaRowCount => "aria-rowcount",
        AttrId::AriaRowIndex => "aria-rowindex",
        AttrId::AriaRowSpan => "aria-rowspan",
        AttrId::AriaSelected => "aria-selected",
        AttrId::AriaSetSize => "aria-setsize",
        AttrId::AriaSort => "aria-sort",
        AttrId::AriaValueMax => "aria-valuemax",
        AttrId::AriaValueMin => "aria-valuemin",
        AttrId::AriaValueNow => "aria-valuenow",
        AttrId::AriaValueText => "aria-valuetext",

        // SVG
        AttrId::AccentHeight => "accentHeight",
        AttrId::AlignmentBaseline => "alignmentBaseline",
        AttrId::ArabicForm => "arabicForm",
        AttrId::AttributeName => "attributeName",
        AttrId::AttributeType => "attributeType",
        AttrId::BaseFrequency => "baseFrequency",
        AttrId::BaselineShift => "baselineShift",
        AttrId::BaseProfile => "baseProfile",
        AttrId::CalcMode => "calcMode",
        AttrId::CapHeight => "capHeight",
        AttrId::ClipPath => "clipPath",
        AttrId::ClipPathUnits => "clipPathUnits",
        AttrId::ClipRule => "clipRule",
        AttrId::ColorInterpolation => "colorInterpolation",
        AttrId::ColorInterpolationFilters => "colorInterpolationFilters",
        AttrId::ColorProfile => "colorProfile",
        AttrId::ColorRendering => "colorRendering",
        AttrId::ContentScriptType => "contentScriptType",
        AttrId::ContentStyleType => "contentStyleType",
        AttrId::DiffuseConstant => "diffuseConstant",
        AttrId::DominantBaseline => "dominantBaseline",
        AttrId::EdgeModeFeConvolveMatrix | AttrId::EdgeModeFeGaussianBlur => "edgeMode",
        AttrId::EnableBackground => "enableBackground",
        AttrId::ExternalResourcesRequired => "externalResourcesRequired",
        AttrId::FillOpacity => "fillOpacity",
        AttrId::FillRule => "fillRule",
        AttrId::FilterRes => "filterRes",
        AttrId::FilterUnits => "filterUnits",
        AttrId::FloodOpacity => "floodOpacity",
        AttrId::FloodColor => "floodColor",
        AttrId::FontFamily => "fontFamily",
        AttrId::FontSize => "fontSize",
        AttrId::FontSizeAdjust => "fontSizeAdjust",
        AttrId::FontStretch => "fontStretch",
        AttrId::FontStyle => "fontStyle",
        AttrId::FontVariant => "fontVariant",
        AttrId::FontWeight => "fontWeight",
        AttrId::GlyphName => "glyphName",
        AttrId::GlyphOrientationHorizontal => "glyphOrientationHorizontal",
        AttrId::GlyphOrientationVertical => "glyphOrientationVertical",
        AttrId::GlyphRef => "glyphRef",
        AttrId::GradientTransform => "gradientTransform",
        AttrId::GradientUnits => "gradientUnits",
        AttrId::HorizAdvX => "horizAdvX",
        AttrId::HorizOriginX => "horizOriginX",
        AttrId::HorizOriginY => "horizOriginY",
        AttrId::ImageRendering => "imageRendering",
        AttrId::KernelMatrix => "kernelMatrix",
        AttrId::KernelUnitLength => "kernelUnitLength",
        AttrId::KeyPoints => "keyPoints",
        AttrId::KeySplines => "keySplines",
        AttrId::KeyTimes => "keyTimes",
        AttrId::LengthAdjust => "lengthAdjust",
        AttrId::LetterSpacing => "letterSpacing",
        AttrId::LightingColor => "lightingColor",
        AttrId::LimitingConeAngle => "limitingConeAngle",
        AttrId::MarkerEnd => "markerEnd",
        AttrId::MarkerHeight => "markerHeight",
        AttrId::MarkerMid => "markerMid",
        AttrId::MarkerStart => "markerStart",
        AttrId::MarkerUnits => "markerUnits",
        AttrId::MarkerWidth => "markerWidth",
        AttrId::MaskContentUnits => "maskContentUnits",
        AttrId::MaskUnits => "maskUnits",
        AttrId::NumOctaves => "numOctaves",
        AttrId::OverlinePosition => "overlinePosition",
        AttrId::OverlineThickness => "overlineThickness",
        AttrId::PaintOrder => "paintOrder",
        AttrId::Panose1 => "panose1",
        AttrId::PathLength => "pathLength",
        AttrId::PatternContentUnits => "patternContentUnits",
        AttrId::PatternTransform => "patternTransform",
        AttrId::PatternUnits => "patternUnits",
        AttrId::PointerEvents => "pointerEvents",
        AttrId::PointsAtX => "pointsAtX",
        AttrId::PointsAtY => "pointsAtY",
        AttrId::PointsAtZ => "pointsAtZ",
        AttrId::PreserveAlpha => "preserveAlpha",
        AttrId::PreserveAspectRatio => "preserveAspectRatio",
        AttrId::PrimitiveUnits => "primitiveUnits",
        AttrId::RefX => "refX",
        AttrId::RefY => "refY",
        AttrId::RenderingIntent => "renderingIntent",
        AttrId::RepeatCount => "repeatCount",
        AttrId::RepeatDur => "repeatDur",
        AttrId::RequiredExtensions => "requiredExtensions",
        AttrId::RequiredFeatures => "requiredFeatures",
        AttrId::ShapeRendering => "shapeRendering",
        AttrId::SolidColor => "solidColor",
        AttrId::SolidOpacity => "solidOpacity",
        AttrId::SpecularConstant => "specularConstant",
        AttrId::SpecularExponent => "specularExponent",
        AttrId::SpreadMethod => "spreadMethod",
        AttrId::StartOffset => "startOffset",
        AttrId::StdDeviationFeDropShadow | AttrId::StdDeviationFeGaussianBlur => "stdDeviation",
        AttrId::StitchTiles => "stitchTiles",
        AttrId::StopColor => "stopColor",
        AttrId::StopOpacity => "stopOpacity",
        AttrId::StrikethroughPosition => "strikethroughPosition",
        AttrId::StrikethroughThickness => "strikethroughThickness",
        AttrId::StrokeDasharray => "strokeDasharray",
        AttrId::StrokeDashoffset => "strokeDashoffset",
        AttrId::StrokeLinecap => "strokeLinecap",
        AttrId::StrokeLinejoin => "strokeLinejoin",
        AttrId::StrokeMiterlimit => "strokeMiterlimit",
        AttrId::StrokeWidth => "strokeWidth",
        AttrId::StrokeOpacity => "strokeOpacity",
        AttrId::SurfaceScale => "surfaceScale",
        AttrId::SystemLanguage => "systemLanguage",
        AttrId::TableValues => "tableValues",
        AttrId::TargetX => "targetX",
        AttrId::TargetY => "targetY",
        AttrId::TextAnchor => "textAnchor",
        AttrId::TextDecoration => "textDecoration",
        AttrId::TextLength => "textLength",
        AttrId::TextRendering => "textRendering",
        AttrId::TransformOrigin => "transformOrigin",
        AttrId::UnderlinePosition => "underlinePosition",
        AttrId::UnderlineThickness => "underlineThickness",
        AttrId::UnicodeBidi => "unicodeBidi",
        AttrId::UnicodeRange => "unicodeRange",
        AttrId::UnitsPerEm => "unitsPerEm",
        AttrId::VAlphabetic => "vAlphabetic",
        AttrId::VectorEffect => "vectorEffect",
        AttrId::VertAdvY => "vertAdvY",
        AttrId::VertOriginX => "vertOriginX",
        AttrId::VertOriginY => "vertOriginY",
        AttrId::VHanging => "vHanging",
        AttrId::VIdeographic => "vIdeographic",
        AttrId::ViewBox => "viewBox",
        AttrId::ViewTarget => "viewTarget",
        AttrId::VMathematical => "vMathematical",
        AttrId::WordSpacing => "wordSpacing",
        AttrId::WritingMode => "writingMode",
        AttrId::XChannelSelector => "xChannelSelector",
        AttrId::XHeight => "xHeight",
        AttrId::XLinkActuate => "xlinkActuate",
        AttrId::XLinkArcrole => "xlinkArcrole",
        AttrId::XLinkHref => "xlinkHref",
        AttrId::XLinkRole => "xlinkRole",
        AttrId::XLinkShow => "xlinkShow",
        AttrId::XLinkTitle => "xlinkTitle",
        AttrId::XLinkType => "xlinkType",
        AttrId::XmlBase => "xmlBase",
        AttrId::XmlLang => "xmlLang",
        AttrId::XmlSpace => "xmlSpace",
        AttrId::YChannelSelector => "yChannelSelector",
        AttrId::ZoomAndPan => "zoomAndPan",
        AttrId::Unknown(QualName {
            prefix: Prefix::XMLNS,
            local,
        }) => {
            if matches!(local.as_str(), "xlink") {
                "xmlnsXlink"
            } else {
                return Err(BuildError::UnsupportedXMLNS(local.to_string()));
            }
        }
        _ => {
            if !attr.prefix().is_empty() {
                return Err(BuildError::UnknownXMLPrefixAttr(attr.clone()));
            }
            let local_name = attr.local_name();
            match local_name.as_str() {
                // HTML
                "accept-charset" => "acceptCharset",
                "accesskey" => "accessKey",
                "allowfullscreen" => "allowFullScreen",
                "autocapitalize" => "autoCapitalize",
                "autocomplete" => "autoComplete",
                "autocorrect" => "autoCorrect",
                "autoplay" => "autoPlay",
                "autosave" => "autoSave",
                "cellpadding" => "cellPadding",
                "cellspacing" => "cellSpacing",
                "charset" => "charSet",
                "classid" => "classID",
                "colspan" => "colSpan",
                "contenteditable" => "contentEditable",
                "contextmenu" => "contextMenu",
                "controlslist" => "controlsList",
                "datetime" => "dateTime",
                "checked" => "defaultChecked",
                "value" => "defaultValue",
                "enctype" => "encType",
                "for" => "htmlFor",
                "formmethod" => "formMethod",
                "formaction" => "formAction",
                "formenctype" => "formEncType",
                "formnovalidate" => "formNoValidate",
                "formtarget" => "formTarget",
                "frameborder" => "frameBorder",
                "http-equiv" => "httpEquiv",
                "inputmode" => "inputMode",
                "itemid" => "itemID",
                "itemprop" => "itemProp",
                "itemref" => "itemRef",
                "itemscope" => "itemScope",
                "itemtype" => "itemType",
                "keyparams" => "keyParams",
                "keytype" => "keyType",
                "marginwidth" => "marginWidth",
                "marginheight" => "marginHeight",
                "maxlength" => "maxLength",
                "mediagroup" => "mediaGroup",
                "minlength" => "minLength",
                "nomodule" => "noModule",
                "novalidate" => "noValidate",
                "playsinline" => "playsInline",
                "radiogroup" => "radioGroup",
                "readonly" => "readOnly",
                "rowspan" => "rowSpan",
                "spellcheck" => "spellCheck",
                "srcdoc" => "srcDoc",
                "srclang" => "srcLang",
                "srcset" => "srcSet",
                "usemap" => "useMap",
                str => {
                    if str.chars().all(char::is_alphanumeric) {
                        return Ok(local_name.clone());
                    }
                    return Err(BuildError::InvalidJSXName(local_name.clone()));
                }
            }
        }
    }
    .into())
}
