[package]
name = "oxvg_serialize"
version = "0.0.7"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../readme.md"
keywords = ["svg", "svgo"]
description = "Serializing primitives for SVG"

[lints]
workspace = true

[dependencies]
cssparser = { workspace = true }
lightningcss = { workspace = true }
