name: rust
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    name: Rust formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Rust formatting
        run: cargo fmt --all --check

  clippy:
    name: Rust check (clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Rust clippy
        run: cargo clippy --workspace --locked

  toml:
    name: Toml formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gwen-lg/taplo-action@v1
        with:
          format: true

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.39.2

  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          # - host: ubuntu-24.04-arm
          #   target: aarch64-unknown-linux-musl
          - host: macos-latest
            target: aarch64-apple-darwin
    name: build - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - name: Run tests
        run: cargo test --verbose --profile release --target=${{ matrix.settings.target }}
      - name: Build
        run: cargo build --verbose --bins --profile release --target=${{ matrix.settings.target }}
      - name: List
        run: ls -R
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ contains(matrix.settings.target, 'windows') }}
        with:
          name: binary-${{ matrix.settings.target }}
          path: target/${{ matrix.settings.target }}/release/oxvg.exe
          if-no-files-found: error
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !contains(matrix.settings.target, 'windows') }}
        with:
          name: binary-${{ matrix.settings.target }}
          path: target/${{ matrix.settings.target }}/release/oxvg
          if-no-files-found: error
